# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0008_auto_20180316_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True, verbose_name='字母')),
                ('cover', models.URLField(verbose_name='链接地址')),
                ('english', models.CharField(max_length=100, verbose_name='英语')),
                ('chinese', models.CharField(max_length=100, verbose_name='中文')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Cover', verbose_name='题图'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='Blogs.Tag', verbose_name='标签'),
        ),
    ]
