# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_auto_20180316_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name': '题图', 'verbose_name_plural': '题图'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='SKYNE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
