# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 01:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_auto_20180323_1135'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
