# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0011_auto_20180518_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Labels',
        ),
    ]
